In [1]:
print("Hola mundo")

Hola mundo


In [2]:
import numpy as np
y = np.array([1,2,3])
x = np.array([4,2,7])
print(x + y)
print(y+2*x)
x/y

[ 5  4 10]
[ 9  6 17]


array([4.        , 1.        , 2.33333333])

In [3]:
import matplotlib.pyplot as plt
plt.show()
import pandas as pd
s = pd.Series([1,2,3,np.nan,6,4,7])
s

0    1.0
1    2.0
2    3.0
3    NaN
4    6.0
5    4.0
6    7.0
dtype: float64

In [4]:
y/x

array([0.25      , 1.        , 0.42857143])

In [5]:
array = [1,2,3,4]
print(type(array))
f = 3
print(type(f))

<class 'list'>
<class 'int'>


In [24]:
#Multidimensional array
xarray = [[2,3,4,5],[12,4,5,9],[67,3,2,2]]
nxarray = np.array(xarray)
print(nxarray)
print(nxarray.shape)

[[ 2  3  4  5]
 [12  4  5  9]
 [67  3  2  2]]
(3, 4)


In [29]:
#matriz 2x2 de ceros
zero = np.zeros((3,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
# array de 5
cinco = np.full((3,3),5)
print(cinco)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [37]:
# array eye
ey = np.eye(6,2)
print(ey)

[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
